services:
  - type: web
    name: crypto-pal-oracle-pro
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build && cd server && npm uninstall -g esbuild && npm uninstall esbuild && rm -rf node_modules package-lock.json && npm install && npx prisma generate && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
